name: Run Discord Bot

on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner type
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt   # Install the dependencies from the requirements file

    - name: Run the bot
      run: |
        source venv/bin/activate
        python Discord-Bot.py   # Replace with the main file of your bot (e.g., bot.py)
      env:
        bot_key: ${{ secrets.MTM2Nzk5Nzg0Nzk3ODM3NzI0Nw.Gvrnb_.AEoPbxnlZeIRBbPyuOUlnDWYeG3PYNZnWp2xaI }}  # Securely load your bot token from GitHub Secrets
